<h1>EC/BEREC form</h2>
<h2> <span class="mw-headline" id="EC.2FBEREC_form:_report_Internet_access_restrictions.2C_get_the_Commission_to_act"> Report Internet access restrictions, get the Commission to act</span></h2>
<p>The EU Commission, along with the European body of telecommunications regulators (BEREC), is holding a <a href="http://ec.europa.eu/information_society/policy/ecomm/current-topics/index_en.htm#Net_Neutrality" class="external text" rel="nofollow">form</a> on Net neutrality violations. They are requesting answers from consumers/citizens, so <b>every citizen and NGO can take action and show that Internet access restrictions are common and widespread all over Europe, to prove a positive legislation is necessary</b>.
</p><p>The deadline is January 20th, but responses to this consultation will surely be accepted beyond that date. In any case, don't let the deadline stop you from answering, we know by experience that some European consultations have accepted responses up to a month and a half after the deadline. (But don't procrastinate either, m'kay?)

</p><p>BEREC have been seen to be tempted to follow the European Commission's failed ”wait-and-see” approach, which pretends there are no Net neutrality problems in Europe, and therefore no need for immediate and positive legislative action.
</p><p>We need to ensure BEREC and the Commission see how many NN violations there are in Europe, and that this fact is in their report to the Commission.
</p>
<h2>This website </h2>
<p>It is intended to provide a gateway for users who seek to report NN violations without the hassle of editing a boring spreadsheet and send an email to an unknown European agency.</p>
<p>All the reports are archived and will be dutyfully sent to the BEREC.</p>
<h2> <span class="mw-headline" id="How_to_answer_the_form">The original form</span></h2>
<p>The form is a .xls spreadsheet you must fill and send back to the BEREC Office:
<a href="mailto:pm@berec.europa.eu" class="external text" rel="nofollow">pm@berec.europa.eu</a>
</p><p>It takes in consideration both fixed and mobile Internet access, as well as both technical and contractual restrictions.<br />
So if a restriction is only mentioned in the contract but not technically enforced, you should report it.
</p>
<ul><li> <a href="http://ec.europa.eu/information_society/policy/ecomm/doc/current/ec_berec_tm_form.xls" class="external text" rel="nofollow">download the form</a>
<ul><li> fixed and mobile Internet are on two different tabs in the spreadsheet

</li></ul>
</li><li> optional, <a href="http://ec.europa.eu/information_society/policy/ecomm/doc/current/ec_berec_tm_instructionstorespondents.pdf" class="external text" rel="nofollow">download BEREC's instructions</a> on how to answer the form
</li><li> fill in the spreadsheet
<ul><li> you may answer in English, French and German, but please use English if you can
</li><li> the yellow cells are for Internet operators only, you do not need to fill them
</li><li> you do not have to answer all the questions / fill in all the cells
</li></ul>
</li><li> send it back in, help save the Internet

</li></ul>
<p>You can and should use the data from <a href="http://respectmynet.eu" class="external text" rel="nofollow">RespectMyNet.eu</a> to help you answer the form.<br />
Many Net neutrality violations have already been reported on RespectMyNet, check the <a href="http://respectmynet.eu/list" class="external text" rel="nofollow">list</a> to find if restrictions that might apply to you.
</p><p>If the Network neutrality violation you are mentioning in the BEREC form is not on RespectMyNet, please add it.
</p><p><b>RespectMyNet will send an answer to the form using the compiled data.</b>
</p><p><b>Everyone must answer, the more answers there are, the better our chances of BEREC telling the Commission that there are many access restrictions, and of the Commission having to act to protect Net neutrality in law.</b>
</p>
<h2> <span class="mw-headline" id="Background_info_and_documents_.26_analysis_from_La_Quadrature">Background info and documents &amp; analysis from La Quadrature</span></h2>

<ul><li> <a href="https://www.laquadrature.net/en/tell-the-eu-regulator-about-your-internet-restrictions" class="external text" rel="nofollow">Tell the EU regulator about your Internet restrictions</a>
</li><li> <a href="https://www.laquadrature.net/en/respectmynet-internet-restrictions-on-the-table-of-eu-regulators" class="external text" rel="nofollow">RespectMyNet: Internet rescrictions on the table of EU regulators</a>
</li><li> <a href="http://www.laquadrature.net/en/la-quadrature-answers-the-eu-form-on-net-neutrality" class="external text" rel="nofollow">Response</a> to the European Net Neutrality consultation.
</li><li> <a href="http://www.laquadrature.net/files/LQDN-20100412-RapportNN.pdf" class="external text" rel="nofollow">Report</a> on Net Neutrality (in French).
</li><li> Take a look also at the latest <a href="http://www.laquadrature.net/en/net-neutrality" class="external text" rel="nofollow">Quad'News</a> related to Net Neutrality.

</li></ul>

