<h1>You received a .csv file as part of BEREC</h1>
<div class="row">
    <div class="span6">
        <h4>This spreadsheet is compatible with Microsoft Excel, as it is a standard for exchanging data between softwares like Lotus, OpenOffice etc.</h4>
        <br /><hr />
        <p>Depending on your OS and version of Microsoft, the file should </p>
        <ol >
            <li>Open immediately in Excel</li>
            <li>Show as a regular spreadsheet</li>
        </ol>
        <br /><hr />
        
    </div>
    <div class="span6">
        <h4>If the file doesn't open immediately or doesn't look like a spreadsheet once opened, follow this guide.</h4>
        <br /><hr />
        <ul class="">
            <li><strong>Not opening: </strong>start Excel, then click on [file]>[open] and select [csv with ; separator] or [all readable files] to open the file</li>
            <li><strong>Not displaying right: </strong>when Excel asks for a column separator, select ";"</li>
            <li><strong>Still not working ?</strong> <a href="support@lqdn.fr">Contact us</a></li>
            <li>
                <a href="http://office.microsoft.com/en-us/excel-help/import-or-export-text-txt-or-csv-files-HP010099725.aspx">
                    Microsoft help
                </a>
            </li>
        </ul>
        <br /><hr />
    </div>
</div>
<h2>Importing data into the original .xls file</h2>
<div class="row">
    <div class="span12">
        <h4>Once opened, you can easily copy/paste ligns from the csv into an existing or new "ec_berec_tm_questionnaire.xls" file</h4>
        <p>The csv columns fit natively with the ones from the original csv file.  </p>
        <p>Again, if you need some help, please <a href="support@lqdn.fr">contact us</a></p>
    </div>
</div>