"Country";"Operator";"Type of measure*";"";"Description of the measure";"Objective";"Method of implementation (if applicable)";"Number of subscribers having a subscription where this measure is implemented";"How is the user informed?";"Can the user activate/deactivate the measure? How?";"Protection of business secret";
<?php
$str = "";
$str = "Test";
// foreach ($this->entries as $entry) {
//     $productsList = $entry["productsList"];
//     $line[] = $entry['dt'];
//     $line[] = $this->rooms[$entry['rooms_id']];
//     $line[] = $this->reportingentry($productsList,'70884001','htSum',true);
//     $line[] = $this->reportingentry($productsList,'70889999','qty');
//     $line[] = $this->reportingentry($productsList,'70882001','qty');
//     $line[] = $this->reportingentry($productsList,'70882001','htSum',true);
//     $line[] = $this->reportingentry($productsList,'70882099','qty');
//     $line[] = $this->reportingentry($productsList,'70882099','htSum',true);
//     $line[] = $this->reportingentry($productsList,'70882002','qty');
//     $line[] = $this->reportingentry($productsList,'70882002','htSum',true);
//     
//     
//     $str .= '"';
//     $str .= implode('";"',$line);
//     $str .= '"';
//     $str .= "\n";
// } 
echo($str);